// <auto-generated />
namespace DotOrg.Mixberry.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201505271101578_ProductGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
