// <auto-generated />
namespace DotOrg.Mixberry.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrepareLocalizationLogic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrepareLocalizationLogic));
        
        string IMigrationMetadata.Id
        {
            get { return "201505301419535_PrepareLocalizationLogic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
